#!/usr/bin/env python3
"""Horonom repository adoption/bootstrap tool (HORO-511).

Makes company-governance adoption cheap and mechanically verifiable for a
Horonom repository, without copying shared policy into it and without
clobbering whatever repo-specific content already exists there.

Mechanism, per ADR-0005 decision #4 (generated projections, no symlinks
into a repo — public cross-platform repos must not depend on fragile
symlink behavior):

  * `CLAUDE.md` (or `.claude/CLAUDE.md`, whichever the repo already uses —
    created at `.claude/CLAUDE.md` for a brand-new repo) gets a small
    **bounded generated region** inserted/refreshed in place — the same
    `<!-- BEGIN GENERATED -->`/`<!-- END GENERATED -->` pattern this repo
    already uses for `SECURITY.md`/`profile/README.md`. Everything outside
    the region is the repo's own content and is never touched.
  * `AGENTS.md` is created fresh, in full, **only if it doesn't already
    exist** — if a repo already has a hand-authored `AGENTS.md`, that's a
    conflict this tool reports rather than silently overwrites.
  * `.horonom-adoption.yaml` records which governance_version was adopted
    and when, for `check` mode's drift detection.

`check` never requires `$HORONOM_WORKSPACE_ROOT` — it only needs the
target repo path, so it works as a CI gate in the adopted repo itself.

`adopt` refuses to run against a repo with uncommitted changes (unless
`--force`) — adoption should never get silently mixed into unrelated
in-flight work. It makes no git commit and no merge; the caller commits
and PRs the result through the normal review process.

Usage:
    python3 scripts/repo_bootstrap.py adopt /path/to/repo --org horonomy
    python3 scripts/repo_bootstrap.py check /path/to/repo
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))
import generate_company_metadata as company_meta  # noqa: E402  (reuse the YAML parser)
import horonom_workspace as hw  # noqa: E402  (reuse load_governance_version)

BLOCK_BEGIN = "<!-- BEGIN GENERATED: horonom_adoption -->"
BLOCK_END = "<!-- END GENERATED: horonom_adoption -->"
AGENTS_MARKER = "<!-- horonom:generated -->"
ADOPTION_MARKER_FILENAME = ".horonom-adoption.yaml"
SCHEMA_VERSION = 1


class AdoptionError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# Content
# ---------------------------------------------------------------------------
def render_adoption_block(*, org: str, repo: str, governance_version: int) -> str:
    return (
        f"{BLOCK_BEGIN}\n"
        f"Read the org baseline first: [horonomy/.github/CLAUDE.md](https://github.com/horonomy/.github/blob/main/CLAUDE.md).\n"
        f"It owns company-wide policy — see [`governance/README.md`](https://github.com/horonomy/.github/blob/main/governance/README.md)\n"
        f"for the full Company -> Product -> Repository precedence rule. This file adds\n"
        f"only what is true of *this* repository (`{org}/{repo}`) and does not repeat the\n"
        f"baseline; it may add to or strengthen a company rule, never weaken a\n"
        f"non-waivable one.\n\n"
        f"Adopted governance_version: {governance_version}. Regenerate this block with\n"
        f"`python3 scripts/repo_bootstrap.py adopt {repo} --org {org}` from a\n"
        f"`horonomy/.github` checkout — do not hand-edit between the markers.\n"
        f"{BLOCK_END}"
    )


def render_agents_md() -> str:
    return (
        f"{AGENTS_MARKER}\n"
        f"<!-- Source: horonomy/.github scripts/repo_bootstrap.py. Do not hand-edit. -->\n\n"
        f"# AGENTS.md\n\n"
        f"Compatibility pointer for tooling that reads `AGENTS.md` instead of\n"
        f"`CLAUDE.md`. This file carries no independent policy content — see\n"
        f"[`CLAUDE.md`](./CLAUDE.md) (or [`.claude/CLAUDE.md`](./.claude/CLAUDE.md)),\n"
        f"the actual entrypoint for this repository (ADR-0005 decision #5: an adapter\n"
        f"never forks a second copy of canonical content).\n"
    )


def render_adoption_marker(*, org: str, repo: str, governance_version: int, adopted_at: str) -> str:
    return (
        "# Generated by scripts/repo_bootstrap.py — do not hand-edit.\n"
        f"schema_version: {SCHEMA_VERSION}\n"
        f"org: {org}\n"
        f"repo: {repo}\n"
        f"governance_version: {governance_version}\n"
        f'adopted_at: "{adopted_at}"\n'
    )


# ---------------------------------------------------------------------------
# CLAUDE.md bounded-region insertion — never touches content outside the markers.
# ---------------------------------------------------------------------------
def find_claude_md(repo: Path) -> Path:
    dot_claude = repo / ".claude" / "CLAUDE.md"
    root_claude = repo / "CLAUDE.md"
    if dot_claude.is_file():
        return dot_claude
    if root_claude.is_file():
        return root_claude
    return dot_claude  # default location for a brand-new repo


def apply_bounded_block(existing_text: str, block: str) -> str:
    pattern = re.compile(re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END), re.DOTALL)
    if pattern.search(existing_text):
        return pattern.sub(block, existing_text, count=1)
    if not existing_text.strip():
        return block + "\n"
    lines = existing_text.splitlines(keepends=True)
    # Insert right after the first line (the repo's own title) so the
    # adoption pointer reads first, before any repo-specific content —
    # matching NEW_REPO_CHECKLIST.md's documented shape.
    return "".join(lines[:1]) + "\n" + block + "\n\n" + "".join(lines[1:])


# ---------------------------------------------------------------------------
# Safety
# ---------------------------------------------------------------------------
def _git_status_clean(repo: Path, *, run_git=None) -> bool:
    """True unless a *tracked* file has an uncommitted change. Untracked
    files are deliberately ignored — a brand-new repo, or one with a few
    just-created scratch files, isn't "in-flight work" in the sense this
    guard exists to protect (mixing adoption into someone's uncommitted
    edit to a tracked file); requiring a fully pristine `git status` would
    also make this tool re-adopt-safe run impossible right after its own
    first run, since that run itself creates new untracked files."""
    run = run_git or (lambda args: subprocess.run(["git", *args], cwd=repo, capture_output=True, text=True, timeout=10))
    result = run(["status", "--porcelain"])
    if result.returncode != 0:
        return False
    tracked_changes = [line for line in result.stdout.splitlines() if not line.startswith("??")]
    return not tracked_changes


# ---------------------------------------------------------------------------
# Adopt
# ---------------------------------------------------------------------------
def adopt(
    repo: Path,
    *,
    org: str,
    governance_version: int | None = None,
    force: bool = False,
    dry_run: bool = False,
    run_git=None,
    now: str | None = None,
) -> dict[str, str]:
    if not (repo / ".git").exists():
        raise AdoptionError(f"{repo} is not a git repository")
    if not force and not _git_status_clean(repo, run_git=run_git):
        raise AdoptionError(
            f"{repo} has uncommitted changes — adoption must not mix into unrelated "
            f"in-flight work. Commit or stash first, or pass --force if you're certain."
        )

    governance_version = governance_version if governance_version is not None else hw.load_governance_version()
    repo_name = repo.name
    adopted_at = now or datetime.now(timezone.utc).isoformat()

    outcomes: dict[str, str] = {}

    claude_path = find_claude_md(repo)
    block = render_adoption_block(org=org, repo=repo_name, governance_version=governance_version)
    existing = claude_path.read_text(encoding="utf-8") if claude_path.exists() else ""
    new_content = apply_bounded_block(existing, block)
    if new_content == existing:
        outcomes["claude_md"] = "unchanged"
    else:
        if not dry_run:
            claude_path.parent.mkdir(parents=True, exist_ok=True)
            claude_path.write_text(new_content, encoding="utf-8")
        outcomes["claude_md"] = "written" if existing else "created"

    agents_path = repo / "AGENTS.md"
    if agents_path.exists():
        current = agents_path.read_text(encoding="utf-8")
        if current.startswith(AGENTS_MARKER):
            expected = render_agents_md()
            outcomes["agents_md"] = "unchanged" if current == expected else "written"
            if current != expected and not dry_run:
                agents_path.write_text(expected, encoding="utf-8")
        else:
            outcomes["agents_md"] = "skipped-conflict"
    else:
        if not dry_run:
            agents_path.write_text(render_agents_md(), encoding="utf-8")
        outcomes["agents_md"] = "created"

    marker_path = repo / ADOPTION_MARKER_FILENAME
    marker_content = render_adoption_marker(org=org, repo=repo_name, governance_version=governance_version, adopted_at=adopted_at)
    if not dry_run:
        marker_path.write_text(marker_content, encoding="utf-8")
    outcomes["adoption_marker"] = "written"

    return outcomes


# ---------------------------------------------------------------------------
# Check (drift) — needs only the target repo, no workspace root.
# ---------------------------------------------------------------------------
def check(repo: Path, *, expected_governance_version: int | None = None) -> list[tuple[str, str, str]]:
    """Returns a list of (name, status, detail) — status in PASS/WARN/FAIL."""
    results: list[tuple[str, str, str]] = []
    expected_governance_version = expected_governance_version if expected_governance_version is not None else hw.load_governance_version()

    marker_path = repo / ADOPTION_MARKER_FILENAME
    if not marker_path.is_file():
        results.append(("adoption_marker", "FAIL", f"{ADOPTION_MARKER_FILENAME} is missing — repo has not been adopted"))
        return results  # nothing else to meaningfully check without it

    try:
        marker = company_meta.parse_yaml(marker_path.read_text(encoding="utf-8"))
    except company_meta.YamlError as exc:
        results.append(("adoption_marker", "FAIL", f"{ADOPTION_MARKER_FILENAME} is malformed: {exc}"))
        return results

    org = marker.get("org")
    repo_name = marker.get("repo", repo.name)
    recorded_version = marker.get("governance_version")
    try:
        recorded_version = int(str(recorded_version))
    except (TypeError, ValueError):
        results.append(("adoption_marker", "FAIL", f"invalid governance_version in {ADOPTION_MARKER_FILENAME}: {recorded_version!r}"))
        return results

    if not org:
        results.append(("adoption_marker", "FAIL", f"{ADOPTION_MARKER_FILENAME} is missing 'org'"))
        return results

    if recorded_version != expected_governance_version:
        results.append(
            ("adoption_marker", "WARN", f"adopted governance_version={recorded_version}, current is {expected_governance_version}")
        )
    else:
        results.append(("adoption_marker", "PASS", f"governance_version={recorded_version} matches current"))

    claude_path = find_claude_md(repo)
    if not claude_path.exists():
        results.append(("claude_md_block", "FAIL", "CLAUDE.md is missing entirely"))
    else:
        text = claude_path.read_text(encoding="utf-8")
        pattern = re.compile(re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END), re.DOTALL)
        match = pattern.search(text)
        if not match:
            results.append(("claude_md_block", "FAIL", "no generated adoption block found in CLAUDE.md"))
        else:
            expected_block = render_adoption_block(org=org, repo=repo_name, governance_version=recorded_version)
            results.append(
                ("claude_md_block", "PASS" if match.group(0) == expected_block else "FAIL", "adoption block matches" if match.group(0) == expected_block else "adoption block content has drifted or was hand-edited")
            )

    agents_path = repo / "AGENTS.md"
    if not agents_path.exists():
        results.append(("agents_md", "WARN", "AGENTS.md is missing"))
    else:
        current = agents_path.read_text(encoding="utf-8")
        if not current.startswith(AGENTS_MARKER):
            results.append(("agents_md", "WARN", "AGENTS.md exists but is not generated — repo-specific, not this tool's concern"))
        elif current != render_agents_md():
            results.append(("agents_md", "FAIL", "AGENTS.md is generated but stale"))
        else:
            results.append(("agents_md", "PASS", "AGENTS.md matches"))

    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _cmd_adopt(args: argparse.Namespace) -> int:
    repo = Path(args.repo).expanduser().resolve()
    try:
        outcomes = adopt(repo, org=args.org, force=args.force, dry_run=args.dry_run)
    except AdoptionError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    for name, outcome in outcomes.items():
        print(f"{name}: {outcome}")
        if outcome == "skipped-conflict":
            print(f"  WARNING: {name} exists with hand-authored content — left untouched.", file=sys.stderr)
    return 1 if "skipped-conflict" in outcomes.values() else 0


def _cmd_check(args: argparse.Namespace) -> int:
    repo = Path(args.repo).expanduser().resolve()
    results = check(repo)
    worst = "PASS"
    for name, status, detail in results:
        print(f"{name}: {status} — {detail}")
        if status == "FAIL":
            worst = "FAIL"
        elif status == "WARN" and worst != "FAIL":
            worst = "WARN"
    print(f"overall: {worst}")
    return 1 if worst == "FAIL" else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p_adopt = sub.add_parser("adopt", help="Adopt or refresh governance in a target repo.")
    p_adopt.add_argument("repo", help="Path to the target repo.")
    p_adopt.add_argument("--org", default="horonomy", help="GitHub org the target repo belongs to (default: horonomy).")
    p_adopt.add_argument("--force", action="store_true", help="Adopt even if the repo has uncommitted changes.")
    p_adopt.add_argument("--dry-run", action="store_true", help="Report what would change without writing anything.")
    p_adopt.set_defaults(func=_cmd_adopt)

    p_check = sub.add_parser("check", help="Report adoption drift; needs only the target repo.")
    p_check.add_argument("repo", help="Path to the target repo.")
    p_check.set_defaults(func=_cmd_check)

    return parser


def main(argv: list[str]) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
