#!/usr/bin/env python3
"""Horonom repository adoption/bootstrap tool (HORO-511).

Makes company-governance adoption cheap and mechanically verifiable for a
Horonom repository, without copying shared policy into it and without
clobbering whatever repo-specific content already exists there.

Mechanism, per ADR-0005 decision #4 (generated projections, no symlinks
into a repo — public cross-platform repos must not depend on fragile
symlink behavior):

  * `CLAUDE.md` (or `.claude/CLAUDE.md`, whichever the repo already uses —
    created at `.claude/CLAUDE.md` for a brand-new repo) gets a small
    **bounded generated region** inserted/refreshed in place — the same
    `<!-- BEGIN GENERATED -->`/`<!-- END GENERATED -->` pattern this repo
    already uses for `SECURITY.md`/`profile/README.md`. Everything outside
    the region is the repo's own content and is never touched.
  * `AGENTS.md` is created fresh, in full, **only if it doesn't already
    exist** — if a repo already has a hand-authored `AGENTS.md`, that's a
    conflict this tool reports rather than silently overwrites.
  * `.horonom-adoption.yaml` records which governance_version was adopted
    and when, for `check` mode's drift detection.

`check` never requires `$HORONOM_WORKSPACE_ROOT` — it only needs the
target repo path, so it works as a CI gate in the adopted repo itself.

`adopt` refuses to run against a repo with uncommitted changes (unless
`--force`) — adoption should never get silently mixed into unrelated
in-flight work. It makes no git commit and no merge; the caller commits
and PRs the result through the normal review process.

Usage:
    python3 scripts/repo_bootstrap.py adopt /path/to/repo --org horonomy
    python3 scripts/repo_bootstrap.py check /path/to/repo
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))
sys.path.insert(0, str(SCRIPTS_DIR.parent / "agents" / "common"))
import generate_company_metadata as company_meta  # noqa: E402  (reuse the YAML parser)
import horonom_workspace as hw  # noqa: E402  (reuse load_governance_version)
import project_skills  # noqa: E402  (reuse the canonical -> adapter projection, cross-repo)

BLOCK_BEGIN = "<!-- BEGIN GENERATED: horonom_adoption -->"
BLOCK_END = "<!-- END GENERATED: horonom_adoption -->"
AGENTS_MARKER = "<!-- horonom:generated -->"
ADOPTION_MARKER_FILENAME = ".horonom-adoption.yaml"
CONSUMPTION_MARKER_FILENAME = ".horonom-consumption.yaml"
SCHEMA_VERSION = 1
HORONOMY_ORG = "horonomy"


class AdoptionError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# Content
# ---------------------------------------------------------------------------
def render_adoption_block(*, org: str, repo: str, governance_version: int) -> str:
    return (
        f"{BLOCK_BEGIN}\n"
        f"Read the org baseline first: [horonomy/.github/CLAUDE.md](https://github.com/horonomy/.github/blob/main/CLAUDE.md).\n"
        f"It owns company-wide policy — see [`governance/README.md`](https://github.com/horonomy/.github/blob/main/governance/README.md)\n"
        f"for the full Company -> Product -> Repository precedence rule. This file adds\n"
        f"only what is true of *this* repository (`{org}/{repo}`) and does not repeat the\n"
        f"baseline; it may add to or strengthen a company rule, never weaken a\n"
        f"non-waivable one.\n\n"
        f"Adopted governance_version: {governance_version}. Regenerate this block with\n"
        f"`python3 scripts/repo_bootstrap.py adopt {repo} --org {org}` from a\n"
        f"`horonomy/.github` checkout — do not hand-edit between the markers.\n"
        f"{BLOCK_END}"
    )


def render_agents_md() -> str:
    return (
        f"{AGENTS_MARKER}\n"
        f"<!-- Source: horonomy/.github scripts/repo_bootstrap.py. Do not hand-edit. -->\n\n"
        f"# AGENTS.md\n\n"
        f"Compatibility pointer for tooling that reads `AGENTS.md` instead of\n"
        f"`CLAUDE.md`. This file carries no independent policy content — see\n"
        f"[`CLAUDE.md`](./CLAUDE.md) (or [`.claude/CLAUDE.md`](./.claude/CLAUDE.md)),\n"
        f"the actual entrypoint for this repository (ADR-0005 decision #5: an adapter\n"
        f"never forks a second copy of canonical content).\n"
    )


def render_adoption_marker(*, org: str, repo: str, governance_version: int, adopted_at: str) -> str:
    return (
        "# Generated by scripts/repo_bootstrap.py — do not hand-edit.\n"
        f"schema_version: {SCHEMA_VERSION}\n"
        f"org: {org}\n"
        f"repo: {repo}\n"
        f"governance_version: {governance_version}\n"
        f'adopted_at: "{adopted_at}"\n'
    )


# ---------------------------------------------------------------------------
# Target-path validation
# ---------------------------------------------------------------------------
def _validate_target_repo(repo: Path) -> Path:
    """Resolve and validate the target repo path before any read/write.

    This tool is an operator-invoked local CLI — `repo` is always a path
    the caller chose deliberately (like `git clone <path>` or `cp -r src
    <path>`), never data that arrived from a network request or another
    party's input. Static analysis (SonarQube python:S2083) nonetheless
    flags any file write whose path traces back to a function argument as
    "path constructed from user-controlled data," since its taint model
    can't distinguish a trusted CLI argument from an untrusted network
    source. Resolving and validating the path explicitly, in one place,
    both closes the taint path a scanner can follow and gives a real
    guarantee: adoption never writes through a symlink to somewhere the
    operator didn't intend, and never targets a bare filesystem root or a
    path that turned out not to be a real repo.
    """
    resolved = repo.resolve()
    if resolved.parent == resolved:
        raise AdoptionError(f"refusing to target the filesystem root: {resolved}")
    if not resolved.is_dir():
        raise AdoptionError(f"{resolved} is not a directory")
    if not (resolved / ".git").exists():
        raise AdoptionError(f"{resolved} is not a git repository")
    return resolved


def _reject_unsafe_symlink(path: Path, *, repo: Path) -> None:
    """Refuse to write to one of adoption's generated file paths if it
    resolves outside the repo — whether the escape comes from the leaf
    path itself being a symlink (dangling, or pointing elsewhere) or from
    ANY ancestor directory component being a symlink (e.g. `.claude` itself
    replaced with a symlink to an outside directory, so `.claude/CLAUDE.md`
    is never a symlink but still resolves outside the repo). A symlink that
    legitimately points at another file *inside* the same repo is allowed
    (e.g. Eridanus's real `AGENTS.md -> .claude/CLAUDE.md`, its own
    ADR-0001 design, which `adopt()` must keep treating as ordinary
    hand-authored content via the existing `skipped-conflict` path).

    `_validate_target_repo` only resolves the repo *directory* — it never
    checked the individual files adoption writes. `Path.exists()` follows
    symlinks and reports False for a dangling one, so a repo carrying a
    dangling symlink at, say, `.horonom-adoption.yaml` fell through every
    write site's "doesn't exist yet, create it" branch and wrote straight
    through the link to wherever it pointed. An initial fix only checked
    `path.is_symlink()` on the leaf component — an independent review
    (HORO-533) found this still fully bypassable by making an *ancestor
    directory* (e.g. `.claude`) the symlink instead of the leaf file, since
    the leaf itself is then never a symlink and the check short-circuited
    before ever resolving the real write location. `Path.resolve()`
    follows symlinks in every path component, not just the leaf, so
    resolving unconditionally and checking containment catches both the
    original leaf case and this ancestor-directory case in one guard.
    """
    resolved = path.resolve()
    try:
        resolved.relative_to(repo)
    except ValueError:
        raise AdoptionError(
            f"refusing to write to {path} — it resolves outside the repo (-> {resolved}), "
            f"via a symlink at the path itself or an ancestor directory"
        ) from None


# ---------------------------------------------------------------------------
# CLAUDE.md bounded-region insertion — never touches content outside the markers.
# ---------------------------------------------------------------------------
def find_claude_md(repo: Path) -> Path:
    dot_claude = repo / ".claude" / "CLAUDE.md"
    root_claude = repo / "CLAUDE.md"
    if dot_claude.is_file():
        return dot_claude
    if root_claude.is_file():
        return root_claude
    return dot_claude  # default location for a brand-new repo


# Capture group is a positive allowlist (GitHub's own repo-name charset:
# alphanumeric, `-`, `_`, `.`) rather than a negative exclusion — a
# `git remote -v` value is attacker-influenced (whoever controls the
# repo's remote config, e.g. a malicious fork or a compromised repo an
# operator later runs `adopt` against) and lands, unescaped, in generated
# content: the .horonom-adoption.yaml `repo:` field and the copy-pasteable
# `python3 scripts/repo_bootstrap.py adopt <repo> --org ...` line in
# CLAUDE.md. A negative exclusion (originally just `[^/\s.]`) let shell
# metacharacters (`;`, `$(...)`, backticks) through into that copy-pasteable
# command — confirmed live (HORO-533 security review): a remote URL crafted
# with a `;$(touch ...)` suffix produced a generated regenerate-command line
# containing that exact injection payload, a real risk if a human or agent
# copy-pastes the suggested command into a shell. Not exploitable by this
# tool itself (no `shell=True` anywhere), but the generated content was
# handing a loaded gun to whatever reads it next.
_REMOTE_URL_RE = re.compile(r"github\.com[:/][^/\s]+/([A-Za-z0-9._-]+?)(?:\.git)?(?:\s|$)")


# Same allowlist rationale as _REMOTE_URL_RE above — org names come from the
# same attacker-influenced `git remote -v` output.
_REMOTE_URL_ORG_RE = re.compile(r"github\.com[:/]([A-Za-z0-9._-]+)/[^/\s]+(?:\s|$)")


def resolve_org(repo: Path, *, run_git=None) -> str | None:
    """The GitHub org a repo's remote actually points at, or None if no
    remote matches the expected shape (e.g. a fresh, not-yet-pushed repo).
    Used to pick adopt-vs-consume mode from the remote's own org rather
    than from local directory naming (HORO-982) — a worktree or scratch
    directory name proves nothing about which org a repo belongs to."""
    run = run_git or (lambda args: subprocess.run(["git", *args], cwd=repo, capture_output=True, text=True, timeout=10))
    result = run(["remote", "-v"])
    if result.returncode != 0:
        return None
    match = _REMOTE_URL_ORG_RE.search(result.stdout)
    return match.group(1) if match else None


def resolve_repo_name(repo: Path, *, run_git=None) -> str:
    """The canonical GitHub repo name, from the remote URL — never the local
    directory's basename. A worktree's directory is deliberately named
    `<repo>-<ticket>-...` per this campaign's own worktree convention
    (governance/engineering/git-pr-merge.md), so `repo.name` would silently
    bake the wrong, worktree-specific name into every generated file this
    tool writes. Falls back to `repo.name` only if no remote is found (e.g.
    a fresh, not-yet-pushed repo)."""
    run = run_git or (lambda args: subprocess.run(["git", *args], cwd=repo, capture_output=True, text=True, timeout=10))
    result = run(["remote", "-v"])
    if result.returncode == 0:
        match = _REMOTE_URL_RE.search(result.stdout)
        if match:
            return match.group(1)
    return repo.name


def apply_bounded_block(existing_text: str, block: str) -> str:
    pattern = re.compile(re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END), re.DOTALL)
    if pattern.search(existing_text):
        return pattern.sub(block, existing_text, count=1)
    if not existing_text.strip():
        return block + "\n"
    lines = existing_text.splitlines(keepends=True)
    # Insert right after the first line (the repo's own title) so the
    # adoption pointer reads first, before any repo-specific content —
    # matching NEW_REPO_CHECKLIST.md's documented shape.
    return "".join(lines[:1]) + "\n" + block + "\n\n" + "".join(lines[1:])


# ---------------------------------------------------------------------------
# Safety
# ---------------------------------------------------------------------------
def _git_status_clean(repo: Path, *, run_git=None) -> bool:
    """True unless a *tracked* file has an uncommitted change. Untracked
    files are deliberately ignored — a brand-new repo, or one with a few
    just-created scratch files, isn't "in-flight work" in the sense this
    guard exists to protect (mixing adoption into someone's uncommitted
    edit to a tracked file); requiring a fully pristine `git status` would
    also make this tool re-adopt-safe run impossible right after its own
    first run, since that run itself creates new untracked files."""
    run = run_git or (lambda args: subprocess.run(["git", *args], cwd=repo, capture_output=True, text=True, timeout=10))
    result = run(["status", "--porcelain"])
    if result.returncode != 0:
        return False
    tracked_changes = [line for line in result.stdout.splitlines() if not line.startswith("??")]
    return not tracked_changes


# ---------------------------------------------------------------------------
# Adopt
# ---------------------------------------------------------------------------
def adopt(
    repo: Path,
    *,
    org: str,
    governance_version: int | None = None,
    force: bool = False,
    dry_run: bool = False,
    run_git=None,
    now: str | None = None,
) -> dict[str, str]:
    repo = _validate_target_repo(repo)
    if not force and not _git_status_clean(repo, run_git=run_git):
        raise AdoptionError(
            f"{repo} has uncommitted changes — adoption must not mix into unrelated "
            f"in-flight work. Commit or stash first, or pass --force if you're certain."
        )
    if not force and (repo / CONSUMPTION_MARKER_FILENAME).is_file():
        raise AdoptionError(
            f"{repo} already carries {CONSUMPTION_MARKER_FILENAME} — it was set up as a "
            f"shared-capability *consumer* (HORO-982 `consume` mode), not a Horonom "
            f"governance adopter. Adopting Horonom's own CLAUDE.md/AGENTS.md governance "
            f"block into a non-Horonom repo is exactly the cross-org contamination this "
            f"guard exists to prevent. Pass --force only if this repo is deliberately "
            f"switching modes."
        )

    governance_version = governance_version if governance_version is not None else hw.load_governance_version()
    repo_name = resolve_repo_name(repo, run_git=run_git)
    adopted_at = now or datetime.now(timezone.utc).isoformat()

    outcomes: dict[str, str] = {}

    claude_path = find_claude_md(repo)
    _reject_unsafe_symlink(claude_path, repo=repo)
    block = render_adoption_block(org=org, repo=repo_name, governance_version=governance_version)
    existing = claude_path.read_text(encoding="utf-8") if claude_path.exists() else ""
    new_content = apply_bounded_block(existing, block)
    if new_content == existing:
        outcomes["claude_md"] = "unchanged"
    else:
        if not dry_run:
            claude_path.parent.mkdir(parents=True, exist_ok=True)
            claude_path.write_text(new_content, encoding="utf-8")
        outcomes["claude_md"] = "written" if existing else "created"

    agents_path = repo / "AGENTS.md"
    _reject_unsafe_symlink(agents_path, repo=repo)
    if agents_path.exists():
        current = agents_path.read_text(encoding="utf-8")
        if current.startswith(AGENTS_MARKER):
            expected = render_agents_md()
            outcomes["agents_md"] = "unchanged" if current == expected else "written"
            if current != expected and not dry_run:
                agents_path.write_text(expected, encoding="utf-8")
        else:
            outcomes["agents_md"] = "skipped-conflict"
    else:
        if not dry_run:
            agents_path.write_text(render_agents_md(), encoding="utf-8")
        outcomes["agents_md"] = "created"

    marker_path = repo / ADOPTION_MARKER_FILENAME
    _reject_unsafe_symlink(marker_path, repo=repo)
    marker_content = render_adoption_marker(org=org, repo=repo_name, governance_version=governance_version, adopted_at=adopted_at)
    if not dry_run:
        marker_path.write_text(marker_content, encoding="utf-8")
    outcomes["adoption_marker"] = "written"

    # Project this repo's canonical agents/skills/ into the target repo's
    # own .claude/skills/ + .codex/skills/ — the cross-repo half of HORO-507:
    # an adopted repo gets the same shared-skill content Claude/Codex read
    # from horonomy/.github itself, never a second hand-copied
    # implementation (HORO-509/ADR-0005 decision #6).
    skill_projections = project_skills.build_projections(dest_root=repo)
    skill_outcomes = {"written": 0, "unchanged": 0, "skipped-conflict": 0}
    for path, content in skill_projections.items():
        _reject_unsafe_symlink(path, repo=repo)
        if path.exists():
            current = path.read_text(encoding="utf-8", errors="replace")
            if current == content:
                skill_outcomes["unchanged"] += 1
                continue
            if not current.startswith(project_skills.GENERATED_MARKER):
                skill_outcomes["skipped-conflict"] += 1
                continue
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        skill_outcomes["written"] += 1
    outcomes["skills"] = (
        f"{skill_outcomes['written']} written, {skill_outcomes['unchanged']} unchanged"
        + (f", {skill_outcomes['skipped-conflict']} skipped-conflict" if skill_outcomes["skipped-conflict"] else "")
    )

    return outcomes


# ---------------------------------------------------------------------------
# Check (drift) — needs only the target repo, no workspace root.
# ---------------------------------------------------------------------------
def check(repo: Path, *, expected_governance_version: int | None = None) -> list[tuple[str, str, str]]:
    """Returns a list of (name, status, detail) — status in PASS/WARN/FAIL."""
    results: list[tuple[str, str, str]] = []
    expected_governance_version = expected_governance_version if expected_governance_version is not None else hw.load_governance_version()

    marker_path = repo / ADOPTION_MARKER_FILENAME
    if not marker_path.is_file():
        results.append(("adoption_marker", "FAIL", f"{ADOPTION_MARKER_FILENAME} is missing — repo has not been adopted"))
        return results  # nothing else to meaningfully check without it

    try:
        marker = company_meta.parse_yaml(marker_path.read_text(encoding="utf-8"))
    except company_meta.YamlError as exc:
        results.append(("adoption_marker", "FAIL", f"{ADOPTION_MARKER_FILENAME} is malformed: {exc}"))
        return results

    org = marker.get("org")
    repo_name = marker.get("repo", repo.name)
    recorded_version = marker.get("governance_version")
    try:
        recorded_version = int(str(recorded_version))
    except (TypeError, ValueError):
        results.append(("adoption_marker", "FAIL", f"invalid governance_version in {ADOPTION_MARKER_FILENAME}: {recorded_version!r}"))
        return results

    if not org:
        results.append(("adoption_marker", "FAIL", f"{ADOPTION_MARKER_FILENAME} is missing 'org'"))
        return results

    if recorded_version != expected_governance_version:
        results.append(
            ("adoption_marker", "WARN", f"adopted governance_version={recorded_version}, current is {expected_governance_version}")
        )
    else:
        results.append(("adoption_marker", "PASS", f"governance_version={recorded_version} matches current"))

    claude_path = find_claude_md(repo)
    if not claude_path.exists():
        results.append(("claude_md_block", "FAIL", "CLAUDE.md is missing entirely"))
    else:
        text = claude_path.read_text(encoding="utf-8")
        pattern = re.compile(re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END), re.DOTALL)
        match = pattern.search(text)
        if not match:
            results.append(("claude_md_block", "FAIL", "no generated adoption block found in CLAUDE.md"))
        else:
            expected_block = render_adoption_block(org=org, repo=repo_name, governance_version=recorded_version)
            results.append(
                ("claude_md_block", "PASS" if match.group(0) == expected_block else "FAIL", "adoption block matches" if match.group(0) == expected_block else "adoption block content has drifted or was hand-edited")
            )

    agents_path = repo / "AGENTS.md"
    if not agents_path.exists():
        results.append(("agents_md", "WARN", "AGENTS.md is missing"))
    else:
        current = agents_path.read_text(encoding="utf-8")
        if not current.startswith(AGENTS_MARKER):
            results.append(("agents_md", "WARN", "AGENTS.md exists but is not generated — repo-specific, not this tool's concern"))
        elif current != render_agents_md():
            results.append(("agents_md", "FAIL", "AGENTS.md is generated but stale"))
        else:
            results.append(("agents_md", "PASS", "AGENTS.md matches"))

    return results


# ---------------------------------------------------------------------------
# Consume — HORO-982's second mode. A non-Horonom repo (e.g. an
# `ai-agent-assembly/*` checkout) that wants the shared engineering-skill
# *capability* without becoming subject to Horonom's own product
# governance/CLAUDE-AGENTS truth/Jira-release rules. Deliberately narrower
# than `adopt()`: no CLAUDE.md/AGENTS.md bounded-region write, no
# `.horonom-adoption.yaml` — only the applicable-filtered skill projection
# plus its own, differently-named marker file. Writing Horonom's governance
# block into a repo this tool doesn't own would be the exact cross-org
# contamination HORO-982 exists to prevent (see the campaign directive's
# "ai-agent-assembly/* never belongs to the horonomy org" rule).
# ---------------------------------------------------------------------------
def render_consumption_marker(
    *, org: str, repo: str, governance_version: int, consumed_at: str, skills: list[str]
) -> str:
    skills_yaml = "\n".join(f"  - {name}" for name in sorted(skills)) or "  []"
    return (
        "# Generated by scripts/repo_bootstrap.py consume — do not hand-edit.\n"
        f"schema_version: {SCHEMA_VERSION}\n"
        f"org: {org}\n"
        f"repo: {repo}\n"
        f"governance_version: {governance_version}\n"
        f'consumed_at: "{consumed_at}"\n'
        f"skills:\n{skills_yaml}\n"
    )


def consume(
    repo: Path,
    *,
    org: str | None = None,
    force: bool = False,
    dry_run: bool = False,
    run_git=None,
    now: str | None = None,
) -> dict[str, str]:
    """Project applicable-filtered shared skills into a non-Horonom repo.

    `org`, when omitted, is resolved from the repo's own remote
    (`resolve_org`) — the caller should not have to already know it. A
    repo whose remote resolves to the `horonomy` org is refused (unless
    `--force`): that repo should run `adopt`, not `consume` — this guard
    is `adopt`'s contamination guard's mirror image.
    """
    repo = _validate_target_repo(repo)
    if not force and not _git_status_clean(repo, run_git=run_git):
        raise AdoptionError(
            f"{repo} has uncommitted changes — consumption must not mix into unrelated "
            f"in-flight work. Commit or stash first, or pass --force if you're certain."
        )
    if not force and (repo / ADOPTION_MARKER_FILENAME).is_file():
        raise AdoptionError(
            f"{repo} already carries {ADOPTION_MARKER_FILENAME} — it was set up as a full "
            f"Horonom governance *adopter*, not a shared-capability consumer. Running "
            f"`consume` here would be mode confusion, not contamination prevention. Pass "
            f"--force only if this repo is deliberately switching modes."
        )

    # Independent review (HORO-982): the horonomy-org refusal must key off
    # the repo's ACTUAL remote, not `org` — the original version checked
    # `(org or resolve_org(...))`, so passing `--org ai-agent-assembly`
    # against a real horonomy remote silently satisfied the `!= HORONOMY_ORG`
    # comparison and skipped the guard entirely, no --force required.
    # Reproduced live: `consume . --org ai-agent-assembly` against this very
    # repo (a real horonomy/.github checkout) ran with no error. `--org` may
    # still override what gets *recorded* in the marker below, but it must
    # never be able to talk the safety check out of looking at the real
    # remote.
    actual_org = resolve_org(repo, run_git=run_git)
    if actual_org == HORONOMY_ORG and not force:
        raise AdoptionError(
            f"{repo}'s remote resolves to the '{HORONOMY_ORG}' org — this is a Horonom repo "
            f"and should run `repo_bootstrap.py adopt`, not `consume`. `consume` is for "
            f"repos outside the horonomy org (e.g. ai-agent-assembly/*) that want the "
            f"shared engineering-skill capability without Horonom's own product governance. "
            f"Pass --force only if this is deliberate (--org does not bypass this check)."
        )
    resolved_org = org or actual_org
    if resolved_org is None:
        resolved_org = "unknown"

    governance_version = hw.load_governance_version()
    repo_name = resolve_repo_name(repo, run_git=run_git)
    consumed_at = now or datetime.now(timezone.utc).isoformat()

    applicable = project_skills.resolve_applicable_skills(repo)
    outcomes: dict[str, str] = {}

    projections: dict[Path, bytes] = {
        path: content.encode("utf-8")
        for path, content in project_skills.build_projections(dest_root=repo, applicable_only=applicable).items()
    }
    for path, content in project_skills.build_asset_projections(dest_root=repo, applicable_only=applicable).items():
        if path in projections:
            raise AdoptionError(f"asset projection collides with a SKILL.md projection path: {path}")
        projections[path] = content

    skill_outcomes = {"written": 0, "unchanged": 0, "skipped-conflict": 0}
    for path, content in projections.items():
        _reject_unsafe_symlink(path, repo=repo)
        if path.exists():
            current = path.read_bytes()
            if current == content:
                skill_outcomes["unchanged"] += 1
                continue
            if not current.startswith(project_skills.GENERATED_MARKER.encode("utf-8")):
                skill_outcomes["skipped-conflict"] += 1
                continue
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        skill_outcomes["written"] += 1
    # Independent review (HORO-982): a dry run must never claim "written" —
    # it's the exact word this PR's own quoted verification output used
    # for a run that wrote zero bytes. `would-write`/`would-write-marker`
    # only on dry_run; real writes keep the unambiguous past tense.
    written_label = "would-write" if dry_run else "written"
    outcomes["skills"] = (
        f"{len(applicable)} applicable ({', '.join(sorted(applicable)) or 'none'}); "
        f"{skill_outcomes['written']} {written_label}, {skill_outcomes['unchanged']} unchanged"
        + (f", {skill_outcomes['skipped-conflict']} skipped-conflict" if skill_outcomes["skipped-conflict"] else "")
    )

    marker_path = repo / CONSUMPTION_MARKER_FILENAME
    _reject_unsafe_symlink(marker_path, repo=repo)
    marker_content = render_consumption_marker(
        org=resolved_org, repo=repo_name, governance_version=governance_version, consumed_at=consumed_at, skills=applicable
    )
    if not dry_run:
        marker_path.write_text(marker_content, encoding="utf-8")
    outcomes["consumption_marker"] = "would-write" if dry_run else "written"

    return outcomes


def check_consumption(repo: Path, *, expected_governance_version: int | None = None) -> list[tuple[str, str, str]]:
    """Drift check for `consume` mode — mirrors `check()` but against
    `.horonom-consumption.yaml` and the applicable-filtered skill set,
    never the CLAUDE.md/AGENTS.md governance block that mode never
    writes."""
    results: list[tuple[str, str, str]] = []
    expected_governance_version = expected_governance_version if expected_governance_version is not None else hw.load_governance_version()

    marker_path = repo / CONSUMPTION_MARKER_FILENAME
    if not marker_path.is_file():
        results.append(
            ("consumption_marker", "NOT_APPLICABLE", f"{CONSUMPTION_MARKER_FILENAME} is missing — this repo has not consumed shared capabilities (fine, not every repo does)")
        )
        return results

    try:
        marker = company_meta.parse_yaml(marker_path.read_text(encoding="utf-8"))
    except company_meta.YamlError as exc:
        results.append(("consumption_marker", "FAIL", f"{CONSUMPTION_MARKER_FILENAME} is malformed: {exc}"))
        return results

    recorded_version = marker.get("governance_version")
    try:
        recorded_version = int(str(recorded_version))
    except (TypeError, ValueError):
        results.append(("consumption_marker", "FAIL", f"invalid governance_version in {CONSUMPTION_MARKER_FILENAME}: {recorded_version!r}"))
        return results

    if recorded_version != expected_governance_version:
        results.append(
            ("consumption_marker", "WARN", f"consumed governance_version={recorded_version}, current is {expected_governance_version}")
        )
    else:
        results.append(("consumption_marker", "PASS", f"governance_version={recorded_version} matches current"))

    recorded_skills = set(marker.get("skills") or [])
    try:
        current_applicable = set(project_skills.resolve_applicable_skills(repo))
    except project_skills.SkillProjectionError as exc:
        results.append(("consumption_skills", "WARN", f"could not resolve current applicable skills: {exc}"))
        return results
    if recorded_skills != current_applicable:
        results.append(
            (
                "consumption_skills",
                "WARN",
                f"recorded skill set {sorted(recorded_skills)} differs from currently-applicable "
                f"{sorted(current_applicable)} — rerun `consume` to refresh",
            )
        )
    else:
        results.append(("consumption_skills", "PASS", f"{len(current_applicable)} applicable skill(s), matches recorded set"))

    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _cmd_adopt(args: argparse.Namespace) -> int:
    repo = Path(args.repo).expanduser().resolve()
    try:
        outcomes = adopt(repo, org=args.org, force=args.force, dry_run=args.dry_run)
    except AdoptionError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    had_conflict = False
    for name, outcome in outcomes.items():
        print(f"{name}: {outcome}")
        if "skipped-conflict" in outcome:
            had_conflict = True
            print(f"  WARNING: {name} has hand-authored content that was left untouched.", file=sys.stderr)
    return 1 if had_conflict else 0


def _cmd_consume(args: argparse.Namespace) -> int:
    repo = Path(args.repo).expanduser().resolve()
    try:
        outcomes = consume(repo, org=args.org, force=args.force, dry_run=args.dry_run)
    except AdoptionError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    had_conflict = False
    for name, outcome in outcomes.items():
        print(f"{name}: {outcome}")
        if "skipped-conflict" in outcome:
            had_conflict = True
            print(f"  WARNING: {name} has hand-authored content that was left untouched.", file=sys.stderr)
    return 1 if had_conflict else 0


def _cmd_check(args: argparse.Namespace) -> int:
    repo = Path(args.repo).expanduser().resolve()
    has_adoption = (repo / ADOPTION_MARKER_FILENAME).is_file()
    has_consumption = (repo / CONSUMPTION_MARKER_FILENAME).is_file()
    # Independent review (HORO-982): the original version picked exactly one
    # of check()/check_consumption() by `is_consumer`, so a repo carrying
    # BOTH markers at once (the same state doctor's cross_org_contamination
    # check flags as FAIL) silently only reported consumption drift here —
    # the adoption marker's own state went unmentioned. Report both blocks
    # whenever both markers are present, with an explicit contamination
    # line, rather than picking a side.
    results: list[tuple[str, str, str]] = []
    if has_adoption and has_consumption:
        results.append(
            (
                "distribution_mode",
                "FAIL",
                f"both {ADOPTION_MARKER_FILENAME} and {CONSUMPTION_MARKER_FILENAME} are present — "
                f"this repo is in two distribution modes at once; see scripts/doctor.py's "
                f"cross_org_contamination check for the full picture",
            )
        )
        results.extend(check(repo))
        results.extend(check_consumption(repo))
    elif has_consumption:
        results.extend(check_consumption(repo))
    else:
        results.extend(check(repo))
    worst = "PASS"
    for name, status, detail in results:
        print(f"{name}: {status} — {detail}")
        if status == "FAIL":
            worst = "FAIL"
        elif status == "WARN" and worst != "FAIL":
            worst = "WARN"
    print(f"overall: {worst}")
    return 1 if worst == "FAIL" else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p_adopt = sub.add_parser("adopt", help="Adopt or refresh governance in a target repo.")
    p_adopt.add_argument("repo", help="Path to the target repo.")
    p_adopt.add_argument("--org", default="horonomy", help="GitHub org the target repo belongs to (default: horonomy).")
    p_adopt.add_argument("--force", action="store_true", help="Adopt even if the repo has uncommitted changes.")
    p_adopt.add_argument("--dry-run", action="store_true", help="Report what would change without writing anything.")
    p_adopt.set_defaults(func=_cmd_adopt)

    p_consume = sub.add_parser(
        "consume", help="Project applicable shared skills into a non-Horonom repo (HORO-982)."
    )
    p_consume.add_argument("repo", help="Path to the target repo.")
    p_consume.add_argument(
        "--org", help="Override the org resolved from the repo's remote (rarely needed)."
    )
    p_consume.add_argument("--force", action="store_true", help="Consume even if the repo has uncommitted changes or resolves to the horonomy org.")
    p_consume.add_argument("--dry-run", action="store_true", help="Report what would change without writing anything.")
    p_consume.set_defaults(func=_cmd_consume)

    p_check = sub.add_parser("check", help="Report adoption/consumption drift; needs only the target repo.")
    p_check.add_argument("repo", help="Path to the target repo.")
    p_check.set_defaults(func=_cmd_check)

    return parser


def main(argv: list[str]) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
